# -*- coding: utf-8 -*-
"""mikolaj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tucsr-u6XYsT-5FYUF9FJpuSeVDI3PVO
"""

# Streamlit app port of the provided matplotlib + ipywidgets Santa drawing
# Run with: streamlit run streamlit_santa.py

import streamlit as st
import matplotlib.pyplot as plt
from matplotlib.patches import Polygon, Circle, Rectangle
import numpy as np

st.set_page_config(page_title="Święty Mikołaj - Interaktywnie", layout="centered")

# --- Funkcja rysująca Mikołaja ---
def draw_santa(r, g, b, beard_length, has_gifts):
    """Rysuje Mikołaja w zależności od parametrów i zwraca fig (matplotlib)."""

    # Konwersja RGB (0-255) na format matplotlib (0.0-1.0)
    costume_color = (r / 255, g / 255, b / 255)

    fig, ax = plt.subplots(figsize=(6, 8))
    ax.set_xlim(-15, 15)
    ax.set_ylim(-20, 20)
    ax.set_aspect('equal')
    ax.axis('off')

    # Stałe
    skin_color = (0.96, 0.87, 0.7)
    white = (1.0, 1.0, 1.0)
    black = (0.0, 0.0, 0.0)
    belt_color = (0.1, 0.1, 0.1)

    # Pozycja bazowa
    base_y = 0

    # 1. Ciało (prostokąt)
    body = Rectangle((-4, base_y - 10), 8, 12, color=costume_color)
    ax.add_patch(body)

    # 2. Pasek (ciemny prostokąt)
    belt = Rectangle((-4, base_y - 1), 8, 2, color=belt_color)
    ax.add_patch(belt)
    # Klamra (żółty kwadrat)
    buckle = Rectangle((-1.5, base_y - 0.5), 3, 1, color='gold')
    ax.add_patch(buckle)

    # 3. Ręce (złączone z ciałem dla uproszczenia)
    arm_l = Rectangle((-7, base_y + 4), 3, 2, color=costume_color)
    arm_r = Rectangle((4, base_y + 4), 3, 2, color=costume_color)
    ax.add_patch(arm_l)
    ax.add_patch(arm_r)

    # 4. Dłonie
    hand_l = Circle((-7, base_y + 5), 1.0, color=skin_color, edgecolor=black)
    hand_r = Circle((7, base_y + 5), 1.0, color=skin_color, edgecolor=black)
    ax.add_patch(hand_l)
    ax.add_patch(hand_r)

    # 5. Głowa (kółko)
    head_center = (0, base_y + 10)
    head = Circle(head_center, 3.5, color=skin_color, edgecolor=black)
    ax.add_patch(head)

    # 6. Czapka
    cap_points = [
        (-4, head_center[1] + 2),
        (4, head_center[1] + 2),
        (2, head_center[1] + 8),
        (0, head_center[1] + 10)
    ]
    cap = Polygon(cap_points, color=costume_color, edgecolor=black)
    ax.add_patch(cap)

    # Futro na czapce
    fur_points = [
        (-4, head_center[1] + 2),
        (4, head_center[1] + 2),
        (4, head_center[1] + 0.5),
        (-4, head_center[1] + 0.5)
    ]
    fur = Polygon(fur_points, color=white, edgecolor=black)
    ax.add_patch(fur)

    # Pompon
    pompon = Circle((0, head_center[1] + 10), 0.8, color=white, edgecolor=black)
    ax.add_patch(pompon)

    # 7. Broda (zależna od beard_length)
    # beard_length jest w zakresie 0..150, mapujemy bezpośrednio na przesunięcie pionowe
    beard_points = [
        (-2.5, head_center[1] - 1),
        (2.5, head_center[1] - 1),
        (3, head_center[1] - 3),
        (1, head_center[1] - 3 - beard_length/10),
        (0, head_center[1] - 4 - beard_length/10), # Najniższy punkt
        (-1, head_center[1] - 3 - beard_length/10),
        (-3, head_center[1] - 3)
    ]
    beard = Polygon(beard_points, color=white, edgecolor=black)
    ax.add_patch(beard)

    # 8. Oczy
    ax.plot([-1.5, 1.5], [head_center[1] + 1, head_center[1] + 1], 'o', color=black, markersize=5)

    # 9. Prezenty
    if has_gifts:
        gift_color_1 = (0.8, 0.2, 0.2)
        gift_color_2 = (0.2, 0.2, 0.8)
        ribbon_color = 'white'

        # Lewy prezent
        gift_l = Rectangle((-10, base_y + 4), 3, 3, color=gift_color_1, edgecolor=black)
        ax.add_patch(gift_l)
        ax.plot([-8.5, -8.5], [4, 7], color=ribbon_color, linewidth=2)
        ax.plot([-10, -7], [5.5, 5.5], color=ribbon_color, linewidth=2)

        # Prawy prezent
        gift_r = Rectangle((7, base_y + 4), 3, 3, color=gift_color_2, edgecolor=black)
        ax.add_patch(gift_r)
        ax.plot([8.5, 8.5], [4, 7], color=ribbon_color, linewidth=2)
        ax.plot([7, 10], [5.5, 5.5], color=ribbon_color, linewidth=2)

    fig.suptitle(f"Święty Mikołaj - Strój: RGB({r}, {g}, {b})", fontsize=14)
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    return fig

# --- Interfejs Streamlit ---
st.title("Święty Mikołaj - edytor stroju (Streamlit)")

st.sidebar.header("Ustawienia Mikołaja")

# Suwaki dla koloru stroju (0-255)
r = st.sidebar.slider("Czerwony (R)", 0, 255, 200)
g = st.sidebar.slider("Zielony (G)", 0, 255, 0)
b = st.sidebar.slider("Niebieski (B)", 0, 255, 0)

# Suwak dla wielkości brody (długość)
beard_length = st.sidebar.slider("Broda (długość)", 0, 150, 100, step=10)

# Pole wyboru dla prezentów
has_gifts = st.sidebar.checkbox("Czy posiada prezenty?", value=True)

# Alternatywnie: pokazać hex color oraz podgląd stroju
if st.sidebar.checkbox("Pokaż kolor w formacie HEX"):
    hex_color = '#%02x%02x%02x' % (r, g, b)
    st.sidebar.write("HEX:", hex_color)
    st.sidebar.color_picker("Podgląd koloru", hex_color)

# Rysujemy i wyświetlamy
fig = draw_santa(r, g, b, beard_length, has_gifts)
st.pyplot(fig)

# Opcjonalnie: możliwość pobrania obrazka jako PNG
buf = None
if st.button("Pobierz obraz jako PNG"):
    import io
    buf = io.BytesIO()
    fig.savefig(buf, format="png", bbox_inches='tight')
    buf.seek(0)
    st.download_button("Kliknij, aby pobrać", data=buf, file_name="santa.png", mime="image/png")

# Krótka instrukcja
st.markdown(
    """
    - Użyj suwaków w bocznym panelu aby zmienić kolor stroju i długość brody.
    - Zaznacz/odznacz 'Czy posiada prezenty?' aby pokazać prezenty.
    - Możesz pobrać aktualny obraz jako PNG.
    """
)